### ISSUE TITLE
Some word in JMDict is missing from Jisho-lens

### ISSUE THREAD

**Issue by wanhuz** [elianiva/jisho-lens#1]
**Problem**

Searching 逢瀬 (おうせ）using Jisho-lens doesn't return any result. But I can confirm that the kanji did in fact exist in latest release of JMDict so I think this is a bug.

**Steps to reproduce**

1. Install Jisho-lens
2. Import database from latest release of 1.0.1
3. Search 逢瀬 in search page
4. No result is returned

**Comment by elianiva** [comment]
fixed in https://github.com/elianiva/jisho-lens/tree/v1.1.0, thanks for reporting!
